version: '3.9'

services:

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak
    restart: always
    ports:
      - "8090:8080"
    environment:      
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: postgres
      KC_DB_USERNAME: postgres
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    env_file:
      - .env
    command: start-dev

  configserver:
    container_name: config-server
    build:
      context: ./spring-config-server
      dockerfile: Dockerfile
    image: configserver:1.0
    restart: always
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka
    env_file:
      - .env

  eureka:
    container_name: eureka
    build:
      context: ./service-discovery
      dockerfile: Dockerfile
    image: eureka:1.0
    restart: always
    ports:
      - "8761:8761"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 4GB
        reservations:
          cpus: '0.25'
          memory: 2GB
  
  gateway:
    container_name: gateway
    build:
      context: ./spring-gateway
      dockerfile: Dockerfile
    image: gateway:1.0
    restart: always
    ports:
      - "9999:9999"
    depends_on:
      - eureka
    environment:
      - SPRING_PROFILES_ACTIVE=service
      - SPRING_CLOUD_CONFIG_FAIL-FAST=true
    env_file:
      - .env

  atomcongresso:
    build:
      context: ./sboot-atom-congresso
      dockerfile: Dockerfile
    image: atomcongresso:1.0
    restart: always
    depends_on:
      - eureka
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONFIG_FAIL-FAST=true
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      resources:
        limits:
          cpus: '0.50'
          memory: 4GB
        reservations:
          cpus: '0.25'
          memory: 2GB

  atomficha:
    build:
      context: ./sboot-atom-ficha
      dockerfile: Dockerfile
    image: atomficha:1.0
    restart: always
    depends_on:
      - eureka
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONFIG_FAIL-FAST=true
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      resources:
        limits:
          cpus: '0.50'
          memory: 4GB
        reservations:
          cpus: '0.25'
          memory: 2GB