version: '3.9'

services:

  configserver:
    container_name: configserver
    #hostname: idcontainer
    build:
      context: ./spring-config-server
      dockerfile: Dockerfile
    image: configserver:1.0
    restart: always
    ports:
      - "8888:8888"
    depends_on:
      - eureka
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME=${SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD=${SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_BASEDIR=${SPRING_CLOUD_CONFIG_SERVER_GIT_BASEDIR}

  eureka:
    container_name: eureka
    #hostname: idcontainer
    build:
      context: ./service-discovery
      dockerfile: Dockerfile
    image: eureka:1.0
    restart: always
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 4GB
        reservations:
          cpus: '0.25'
          memory: 2GB
  
  gateway:
    container_name: gateway
    #hostname: idcontainer
    build:
      context: ./spring-gateway
      dockerfile: Dockerfile
    image: gateway:1.0
    restart: always
    ports:
      - "9999:9999"
    depends_on:
      - eureka
    environment:
      - SPRING_PROFILES_ACTIVE=service
      - SPRING_CLOUD_CONFIG_FAIL-FAST=true

  atomcongresso:
    build:
      context: ./sboot-atom-congresso
      dockerfile: Dockerfile
    image: atomcongresso:1.0
    restart: always
    # ports:
    #   - "8080"
    depends_on:
      - eureka
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONFIG_FAIL-FAST=true
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: vip
      resources:
        limits:
          cpus: '0.50'
          memory: 4GB
        reservations:
          cpus: '0.25'
          memory: 2GB

  atomficha:
    build:
      context: ./sboot-atom-ficha
      dockerfile: Dockerfile
    image: atomficha:1.0
    restart: always
    # ports:
    #   - "8080"
    depends_on:
      - eureka
    environment:
      - SPRING_CLOUD_CONFIG_FAIL-FAST=true
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: vip
      resources:
        limits:
          cpus: '0.50'
          memory: 4GB
        reservations:
          cpus: '0.25'
          memory: 2GB